spring.application.name=onsen-review-app

# \u81EA\u5206\u306EPC\u5C02\u7528\u306EDB\u8A2D\u5B9A\u30D5\u30A1\u30A4\u30EB\u3092\u8AAD\u307F\u8FBC\u3080
spring.config.import=optional:classpath:application-local.properties

# JPA\u8A2D\u5B9A
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true